import Head from "next/head";
import Header from "~/app/_components/header";
import { api } from "~/trpc/server";

export default async function Page({
  params,
}: {
  params: { sessionId: string };
}) {
  const { sessionId } = params;
  const currentSession = await api.chatbot.getSession.query({
    sessionId: parseInt(sessionId),
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col">
        <Header />
        <div className="flex flex-col">
          {currentSession.state === "NOT_STARTED" && (
            <button className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">
              Start the Case
            </button>
          )}
        </div>
      </main>
    </>
  );
}
